### ISSUE TITLE
Compare results of Pandas implementation of TA-Lib with results of TA-Lib Python wrapper

### ISSUE THREAD

**Issue by femtotrader** [llazzaro/analyzer#8]
Hello,

I noticed

https://github.com/llazzaro/analyzer/blob/master/analyzer/pyTaLib/pandasImpl.py

maybe you should put a link to your project at https://www.quantopian.com/posts/technical-analysis-indicators-without-talib-code (at least about the TA-Lib part)

You might try to compare results from this Pandas implementation of TA Lib and results of TA-Lib wrapper.

https://github.com/mrjbq7/ta-lib

Some issues can also apply to this code

https://github.com/mrjbq7/ta-lib/issues/66
https://github.com/mrjbq7/ta-lib/issues/68

I wonder if just the TA-Lib pandas shouldn't be a standalone project.

Kind regards

**Comment by femtotrader** [comment]
I've just create a GitHub project to manage technical analysis indicators (Pandas implementation)

https://github.com/femtotrader/pandas_talib

it's a work in progress.

I need to save price data as CSV to use it for unit tests.

**Comment by llazzaro** [comment]
I will take a look to that project. I want to keep analyzer as simple as possible.

**Comment by llazzaro** [comment]
ok I will remove pyTalib inside analyzer. your lib will be used in https://github.com/llazzaro/analyzerstrategies

thanks!

**Comment by femtotrader** [comment]
Thanks but don't forget that "my" lib still have some issues
see https://github.com/femtotrader/pandas_talib/issues

https://github.com/mrjbq7/ta-lib/ should also be considered
